config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'pages/about'
  get 'static/error'
  get '/biodiversity_dashboard', to: 'dashboards#biodiversity'

  constraints ->(request) { request.env['warden'].user } do
    #              ☝🏻 current HTTP request object
    #                  Returns Raw Reck Env: Rack is a low-level interface between web servers that support Ruby and Ruby frameworks.
    #                          ☝🏻 Essentially, every Rails application is also a Rack application
    #                         .user fetches the currently authenticated user
    root 'dashboards#index', as: :authenticated_root
  end

  root 'pages#about'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/dashboards', to: 'dashboards#index'
  get '/appearance', to: 'dashboards#appearance'

  get '/links/:id/track_click', to: 'links#track_click', as: :track_link_click

  get '/error', to: 'static#error', as: :error

  # QR Codes that lead to App Stores
  get '/app_stores', to: 'pages#app_stores', as: :app_stores
  get '/app_stores_buttons', to: 'pages#app_stores_buttons', as: :app_stores_buttons

  # Gets the id as a parameter to our dashboards_controller within the index action
  # Allows us to use user_path(user) to get the URL for a user's profile page
  get ':id', to: 'dashboards#show', as: :user

  resources :links, only: %i[create update]

  get '/download_vcard/:name', to: 'vcards#download', as: :download_vcard
end

app/controllers/dashboards_controller.rb
# frozen_string_literal: true

class DashboardsController < ApplicationController
  before_action :authenticate_user!, except: %i[show biodiversity]
  before_action :set_user, only: [:show]

  def index
    @should_render_navbar = true
    @links = current_user.links
    @user = current_user
    @empty_links = current_user.missing_links
  end

  def appearance
    @should_render_navbar = true
    @links = current_user.links
    @user = current_user
    current_user.build_linktree_customization unless current_user.linktree_customization
  end

  def show
    redirect_to dashboards_path if @user.nil?

    @links = @user.links
  end

  def biodiversity; end

  private

  def set_user
    @user = User.friendly.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:full_name, :username, :body, :avatar)
  end
end

app/helpers/dashboards_helper.rb
# frozen_string_literal: true

module DashboardsHelper
end

app/views/dashboards/appearance.html.erb
<div class="container text-white dashboard-container">
  <div class="row">
    <h1 style="text-align:left;">Edit your page's appearance!✍🏻</h1>
    <!-- Left Side: Linktree Form -->
    <div class="col-md-6 linktree-form">
      <%= simple_form_for(current_user,
        url: registration_path(current_user),
        html: {method: :put},
        data: {turbo: false}) do |f|  %>
        <div class="row">
          <div class="col-12 link-list">
            <div class="row mt-5">
              <div class="col-12">
                <%= cl_image_tag current_user.avatar.key, class: "avatar-image" if current_user.avatar.attached?  %>
              </div>
              <div class="col-12 mt-5 upload-photo">
                <%= f.input :avatar, required: false, input_html: { class: 'd-none'}, label_html: { class: 'upload-photo p'}, label: '📷 Upload a photo' %>
              </div>
            </div>
            <div class="row mt-5">
              <div class="col-12">
                <%= f.input :full_name, placeholder: "Linktree Title", label: false, class:"form-control", required: false %>
              </div>
              <div class="col-12">
                <div class="input-group mb-3 flex-nowrap">
                  <span style="height: 61px;" class="input-group-text d-flex align-items-center">@</span>
                  <%= f.input :username,
                              placeholder: "Your username..",
                              label: false,
                              wrapper_html: { class: "flex-grow-1" },
                              required: true %>
                </div>
              </div>
            </div>
            <div class="row mt-5">
              <div class="col">
                <%= f.input :body, placeholder: "About you..", label: false, class:"form-control", required: false %>
              </div>
            </div>
            <%= f.simple_fields_for :linktree_customization do |ltc| %>
              <div class="row">
                <%# LinktreeCustomization %>
                <%= f.simple_fields_for :linktree_customization do |ltc| %>
                  <div class="row">
                    <div class="col-6">
                      <%= ltc.input :theme, label: 'Theme', placeholder: "dark" %>
                    </div>
                    <div class="col-6">
                      <%= ltc.input :background_color, label: 'Background Color', placeholder: "#89CFF0" %>
                    </div>
                    <div class="col-6">
                      <%= ltc.input :link_shape, label: 'Link Shape', placeholder: "round" %>
                    </div>
                    <div class="col-6">
                      <%= ltc.input :link_color, label: 'Link Color', placeholder: "#89CFF0" %>
                    </div>
                    <div class="col-6">
                      <%= ltc.input :link_font_color, label: 'Link Font Color', placeholder: "#89CFF0" %>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
            <div class="col-6 no-padding-col mt-5">
              <%= f.submit "Update Account", class: "btn btn-dark" %>
            </div>
          </div>
        </div>
      <% end %>
      <br>
      <%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: "delete"}, class:"btn btn-danger mb-3" %>
    </div>

    <!-- Right Side: Linktree Preview -->
    <div class="col-md-6 linktree-preview">
      <div class="phone-preview mt-5">
        <div class="container">
          <div class="row mt-5">
            <div class="col-12 d-flex justify-content-center">
              <%= image_tag(@user.avatar, class:"avatar") if @user.avatar.attached?  %>
            </div>
            <div class="col-12 mt-3">
              <div class="d-flex justify-content-center">
                <h3><%= @user.full_name %></h3>
              </div>
            </div>
            <div class="col-12 mb-3">
              <div class="d-flex justify-content-center">
                <p><%= @user.body %></p>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-12">
              <% @links.each do |link| %>
                <% unless link.url.empty? %>
                  <div class="row">
                    <div class="col-12 d-flex justify-content-center">
                      <%= link_to link.url, target:"_blank", class:"linkable btn btn-secondary" do %>
                        <span class="linkable-span linkable-font"><%= link.title %></span>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <%= link_to 'View my Linktree', user_path(@user), class: 'mt-4 view-linktree btn btn-custom' %>
    </div>

  </div>
</div>

app/views/dashboards/biodiversity.html.erb
<div class="container text-center my-5">
  <h1 class="mb-4">Biodiversity Dashboard</h1>
    <p>
      <%= link_to 'Download Dashboard', asset_path('Biodiversity Dashboard.png'), download: "Biodiversity Dashboard", class: 'btn btn-custom' %>
    </p>
</div>
<div class="dashboard-image">
  <%= image_tag 'Biodiversity Dashboard.png',
    alt: "Biodiversity Dashboard",
    class: 'img-responsive',
    style: 'width: 100vw;'
  %>
</div>

app/views/dashboards/index.html.erb
  <div class="container background-container">
    <div class="container">
      <div class="row">
            <h1>Welcome to your Linktree Dashboard & Manager 🐝</h1>
            <p>You can edit your Linktree here!</p>

          <div class="col-6 mt-2">
          <%# Future Col %>
        <%# <div class="col-3"> %>
        <%# New Design goes here %>
            <% @links.each do |link| %>
              <%= simple_form_for link do |f| %>
              <%= f.input :title, placeholder: "Title", label: false, class:"form-control" %>
              <%= f.input :url, placeholder: "URL", label: false, class:"form-control" %>
              <%= f.submit class:"btn btn-custom me-auto mb-2" %>
              <% end  %>
            <% end  %>

            <% @empty_links.each do |link| %>
              <%= simple_form_for link do |f| %>
              <%= f.input :title, placeholder: "Title", label: false, class:"form-control", input_html: { autofocus: true } %>
              <%= f.input :url, placeholder: "URL", label: false, class:"form-control" %>
              <%= f.submit class:"btn btn-custom me-auto mb-2" %>
              <% end  %>
            <% end  %>
          <%# </div> %>
        </div>


         <!-- Right Side: Linktree Preview -->
          <div class="col-md-6 linktree-preview">
            <%= link_to 'View my Linktree', user_path(@user), class: 'mx-2 view-linktree btn btn-custom' %>
            <div class="phone-preview mt-5">
              <div class="container">
                <div class="row mt-5">
                  <div class="col-12 d-flex justify-content-center">
                    <%= image_tag(@user.avatar, class:"avatar") if @user.avatar.attached?  %>
                  </div>
                  <div class="col-12 mt-3">
                    <div class="d-flex justify-content-center">
                      <h3><%= @user.full_name %></h3>
                    </div>
                  </div>
                  <div class="col-12 mb-3">
                    <div class="d-flex justify-content-center">
                      <p><%= @user.body %></p>
                    </div>
                  </div>
                </div>
                <div class="row">
                  <div class="col-12">
                    <% @links.each do |link| %>
                      <% unless link.url.empty? %>
                        <div class="row">
                          <div class="col-12 d-flex justify-content-center">
                            <%= link_to link.url, target:"_blank", class:"linkable btn btn-secondary" do %>
                              <span class="linkable-span linkable-font"><%= link.title %></span>
                            <% end %>
                          </div>
                        </div>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          </div>
      </div>
    </div>
  </div>

app/views/dashboards/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-1"></div>
      <div class="col-10">
        <div class="row mt-5">
          <div class="col-12 d-flex justify-content-center">
            <%= image_tag(@user.avatar, class:"avatar") if @user.avatar.attached?  %>
          </div>
          <div class="col-12 d-flex justify-content-center mt-3">
            <h1><%= @user.full_name %></h1>
          </div>
          <div class="col-12 d-flex justify-content-center mb-3">
            <h2><%= @user.body %></h2>
        </div>
      </div>
    <div class="col-1"></div>
      <div class="row">
        <div class="col-1"></div>
          <div class="col-10">
          <% @links.each do |link|  %>
            <% unless link.url.empty? %>
              <div class="row">
                <div class="col-12 d-flex justify-content-center">
                  <%= link_to track_link_click_path(link), target:"_blank", class:"linkable btn btn-secondary" do %>
                    <span class="linkable-span linkable-font"><%= link.title %></span>
                  <% end %>
                </div>
              </div>
            <% else %>
            <%= nil %>
            <% end %>
          <% end %>
          </div>
        <div class="col-1"></div>
      </div>
    </div>
  </div>
</div>