config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'pages/about'
  get 'static/error'
  get '/biodiversity_dashboard', to: 'dashboards#biodiversity'

  constraints ->(request) { request.env['warden'].user } do
    #              ☝🏻 current HTTP request object
    #                  Returns Raw Reck Env: Rack is a low-level interface between web servers that support Ruby and Ruby frameworks.
    #                          ☝🏻 Essentially, every Rails application is also a Rack application
    #                         .user fetches the currently authenticated user
    root 'dashboards#index', as: :authenticated_root
  end

  root 'pages#about'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get '/dashboards', to: 'dashboards#index'
  get '/appearance', to: 'dashboards#appearance'

  get '/links/:id/track_click', to: 'links#track_click', as: :track_link_click

  get '/error', to: 'static#error', as: :error

  # QR Codes that lead to App Stores
  get '/app_stores', to: 'pages#app_stores', as: :app_stores
  get '/app_stores_buttons', to: 'pages#app_stores_buttons', as: :app_stores_buttons

  # Gets the id as a parameter to our dashboards_controller within the index action
  # Allows us to use user_path(user) to get the URL for a user's profile page
  get ':id', to: 'dashboards#show', as: :user

  resources :links, only: %i[create update]

  get '/download_vcard/:name', to: 'vcards#download', as: :download_vcard
end

app/views/layouts/_alerts.html.erb
<%# app/views/layouts/_alerts.html.erb %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">

    <%# Brand Logo %>
    <a class="navbar-brand" href="#">
      <% if current_user.avatar.attached?  %>
        <%= cl_image_tag current_user.avatar.key, width: "30", crop: "fill", class: "d-inline-block align-text-top rounded-circle" %>
      <% else %>
        <%= image_tag 'hivetracks_logo.png', width: "30", height: "30", class: "d-inline-block align-text-top" %>
      <% end %>
      <%= link_to "LinkTree Builder", dashboards_path, class: "navbar-brand p"  %>
    </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%# Navbar %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Appearance", appearance_path, class: "nav-link p"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Links", dashboards_path, class: "nav-link p"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Analytics", rails_admin_path, class: "nav-link p"  %>
        </li>
        <li class="nav-item">
          <%= link_to "Settings", edit_user_registration_path, class: "nav-link p"  %>
        </li>
      </ul>

      <%# Dropdown %>
      <ul class="navbar-nav mr-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.username  %>
          </a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <li><%= link_to "My Account", edit_user_registration_path, class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
                <li><%= link_to "My Linktree", user_path(@user), class: "dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Log Out", destroy_user_session_path, data: {turbo_method: "delete"}, class:"dropdown-item" %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HiveTracks Linktree</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="theme-color" content="#0f2e33">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= render 'shared/ios_pwa_links' %>
    <link rel="manifest" href="<%= asset_path 'manifest.json' %>">
  </head>

  <style>
    body {
      /* HiveTracks Background Gradient */
      background: radial-gradient(50% 50.00% at 50.00% 50.00%, #5F8264 0%, rgba(15, 46, 51, 0.74) 100%), var(--ht-light-green, #5F8264);
      height: 100vh !important;
      }
  </style>

  <body>
    <%= render partial: 'layouts/navbar' if @should_render_navbar %>
    <%= render partial: 'layouts/alerts'  %>
    <%= yield %>
  </body>
</html>